# Update all mentions of this name in vercel-packages when changing.
name: build-and-deploy

on:
  push:
  # we need the preview tarball for deploy tests
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  deploy-target:
    runs-on: ubuntu-latest
    outputs:
      deploy-target: ${{ steps.deploy-target.outputs.value }}
      release-type: ${{ steps.deploy-target.outputs.release-type }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Setup corepack
        run: |
          npm i -g corepack@0.31
          corepack enable
      - name: Determine deploy target
        # 'force-preview' performs a full preview build but only if acknowledged i.e. workflow_dispatch
        # 'automated-preview' for pushes on branches other than 'canary' for integration testing.
        # 'staging' for canary branch since that will eventually be published i.e. become the production build.
        id: deploy-target
        run: |
          RELEASE_CHECK=$(node ./scripts/check-is-release.js 2> /dev/null || :)
          echo "RELEASE_CHECK is $RELEASE_CHECK"

          if [[ $RELEASE_CHECK == 'new-release' ]]; then
            echo "value=production" >> $GITHUB_OUTPUT
            echo "release-type=new-release" >> $GITHUB_OUTPUT
          elif [[ $RELEASE_CHECK == v* ]]; then
            echo "value=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/canary" ]]; then
            echo "value=staging" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "value=force-preview" >> $GITHUB_OUTPUT
          elif [[ $(node scripts/run-for-change.js --not --type docs --exec echo 'false') != 'false' ]]; then
            echo "value=skipped" >> $GITHUB_OUTPUT
          else
            echo "value=automated-preview" >> $GITHUB_OUTPUT
          fi
      - name: Print deploy target
        run: echo "Deploy target is '${{ steps.deploy-target.outputs.value }}'"

  publishRelease:
    if: ${{ needs.deploy-target.outputs.deploy-target == 'production' && github.event_name == 'push' && (github.ref == 'refs/heads/canary' || github.ref == 'refs/heads/release/dry-run') }}
    name: Potentially publish release
    runs-on: ubuntu-latest
    needs:
      - deploy-target
    permissions:
      contents: write
      id-token: write
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Setup corepack
        run: |
          npm i -g corepack@0.31
          corepack enable

      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - run: npm i -g npm@10.4.0 # need latest version for provenance (pinning to avoid bugs)
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # Legacy release process
      - run: ./scripts/publish-release.js
        if: ${{ needs.deploy-target.outputs.release-type != 'new-release' }}
        env:
          RELEASE_BOT_GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

      # New release process
      - name: Publish to NPM
        id: changesets
        # TODO: Change to IS_RELEASE condition when new release becomes stable.
        if: ${{ needs.deploy-target.outputs.release-type == 'new-release' }}
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
          # Don't create GH release when is dry run. There is no good way to test
          # GH Release as draft yet depending on changesets/action.
          createGithubReleases: ${{ github.ref != 'refs/heads/release/dry-run' }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          DRY_RUN: ${{ github.ref == 'refs/heads/release/dry-run' }}
