# Update all mentions of this name in vercel-packages when changing.
name: build-and-deploy

on:
  push:
  # we need the preview tarball for deploy tests
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  publishRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Setup corepack
        run: |
          npm i -g corepack@0.31
          corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Determine deploy target
        # 'force-preview' performs a full preview build but only if acknowledged i.e. workflow_dispatch
        # 'automated-preview' for pushes on branches other than 'canary' for integration testing.
        # 'staging' for canary branch since that will eventually be published i.e. become the production build.
        id: deploy-target
        run: |
          # TODO: Remove the new release check once the new release workflow is fully replaced.
          RELEASE_CHECK=$(node ./scripts/check-is-release.js 2> /dev/null || :)
          if [[ $RELEASE_CHECK = "new-release" ]];
          then
            echo "__NEW_RELEASE=true" >> $GITHUB_ENV
          elif [[ $RELEASE_CHECK = v* ]];
          then
            echo "value=production" >> $GITHUB_OUTPUT
          elif [ '${{ github.ref }}' == 'refs/heads/canary' ]
          then
            echo "value=staging" >> $GITHUB_OUTPUT
          elif [ '${{ github.event_name }}' == 'workflow_dispatch' ]
          then
            echo "value=force-preview" >> $GITHUB_OUTPUT
          elif [[ $(node scripts/run-for-change.js --not --type docs --exec echo 'false') != 'false' ]];
          then
            echo "value=skipped" >> $GITHUB_OUTPUT
          else
            echo "value=automated-preview" >> $GITHUB_OUTPUT
          fi
      - name: Print deploy target
        run: echo "Deploy target is '${{ steps.deploy-target.outputs.value }}'"

      # New release process
      - name: Publish to NPM
        if: ${{ steps.deploy-target.outputs.value != 'skipped' }}
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
          # Don't create GH release when is dry run. There is no good way to test it
          # as draft depending on changesets/action ATM.
          createGithubReleases: ${{ github.ref != 'refs/heads/release/dry-run' }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          DRY_RUN: ${{ github.ref == 'refs/heads/release/dry-run' }}

      - name: Print published packages
        if: ${{ steps.deploy-target.outputs.value != 'skipped' }}
        run: echo '{"published":${{ steps.changesets.outputs.published }}}'
