
name: Run

on:
  workflow_dispatch:

env:
  __TESTING: 'false'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: node index.js
      - run: |
          echo "Shell command: $__TESTING"
          echo "Workflow expression: ${{ env.__TESTING }}"