
name: Run

on:
  workflow_dispatch:

env:
  __TESTING: 'false'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          if [[ $(node ./scripts/check-is-release.js 2> /dev/null || :) =~ ^Version\ Packages\ (canary|release-candidate|stable)$ ]]; then
            echo "__TESTING=true" >> $GITHUB_ENV
          else
            echo "Not matching. Got: $(node ./scripts/check-is-release.js 2> /dev/null || :)"
          fi
      - run: |
          echo "Shell command: $__TESTING"
          echo "Workflow expression: ${{ env.__TESTING }}"