name: Update Version

on:
  schedule:
    # run every 30 min
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/canary'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true

      - name: Setup corepack
        run: |
          npm i -g corepack@0.31
          corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Run changeset version
        run: pnpm changeset version

      - name: Re-install to prevent lockfile diff
        run: pnpm install

      - name: Commit if has changes
        run: node ./scripts/commit-if-has-change.js
        env:
          RELEASE_BOT_GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

